name: e2e

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:

  e2e:
    name: e2e_${{ matrix.k8s }}_${{ matrix.ipFamily }}_${{ matrix.server }}_${{ matrix.agent }}
    runs-on: ubuntu-20.04
    timeout-minutes: 100
    uses: ./.github/workflows/e2e_template.yaml
    strategy:
      fail-fast: false
      matrix:
        server: ["latest","0.29.2"]
        agent: ["latest","0.29.2"]
        # 有 exclue 的话有45个job  没有exclue的话有81个job 3*3*3*3
        exclude:
        - server: "0.29.2"
          agent: "0.29.2"
        # server: ["latest"]
        # agent: ["latest"]
        # include:
        # - versions: latest-latest
        # - versions: latest-0.29.2
        # - versions: latest-0.28.2
        # - versions: 0.29.2-latest
        # - versions: 0.28.2-latest

        # - server: latest
        #   agent: 0.29.2
        # - server: latest
        #   agent: 0.28.2
        # - server: 0.29.2
        #   agent: latest
        # - server: 0.28.2
        #   agent: latest
    with:
      ref: master
      serverVersion: ${{ matrix.server }}
      agentVersion: ${{ matrix.agent }}

  release-029-skew:
    name: release-029-skew
    runs-on: ubuntu-20.04
    timeout-minutes: 100
    strategy:
      fail-fast: false
      matrix:
        server: ["0.29.2"]
        agent: ["latest","0.29.2","0.28.2"]
    uses: ./.github/workflows/e2e_template.yaml
    with:
      ref: master
      serverVersion: ${{ matrix.server }}
      agentVersion: ${{ matrix.agent }}

  release-030-skew:
    name: release-030-skew
    runs-on: ubuntu-20.04
    timeout-minutes: 100
    strategy:
      fail-fast: false
      matrix:
        server: ["0.30.0"]
        agent: ["latest","0.29.2","0.28.2"]
    uses: ./.github/workflows/e2e_template.yaml
    with:
      ref: master
      serverVersion: ${{ matrix.server }}
      agentVersion: ${{ matrix.agent }}
